name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Set the Java distribution
          java-version: '17'        # Specify the Java version

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        shell: bash
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install dependencies
        run: dotnet restore src/TodoApi.csproj

      - name: Build the solution
        run: dotnet build --no-restore src/TodoApi.csproj

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"devops39_dotnet-todo" /o:"devops39" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build src/TodoApi.csproj
          dotnet sonarscanner end
