name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Code Analysis with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.7
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=myprojectkey
            -Dsonar.organization=myorganization
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag myapp:${{ github.sha }} <your-docker-repo>/myapp:${{ github.sha }}
          docker push <your-docker-repo>/myapp:${{ github.sha }}
