name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarCloud Scanner Globally
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd src # Adjust this if your .csproj is in a different directory
          dotnet-sonarscanner begin /k:"dotnet-todo_dotnet" /o:"dotnet-todo" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build --configuration Release
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build Docker image
        run: |
          docker build -t devops39/dotnet-todo:latest -f src/Dockerfile .
          docker tag devops39/dotnet-todo:latest devops39/dotnet-todo:v1.0.0

      - name: Semantic Versioning
        id: vars
        run: |
          echo "GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(echo v1.0.${{ steps.vars.outputs.build_number }})" >> $GITHUB_ENV
