name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Run Code Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/Language-Specific/JavaScript"

      - name: Push Docker Image
        run: echo "Push Docker image command here"
