name: minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Docker image
        run: docker build -t dotnet-todo:${{ github.sha }} .

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat

      - name: Set up Minikube with Docker Driver
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/
          minikube start --driver=docker --kubernetes-version=v1.21.14

      - name: Deploy to Minikube using Helm
        run: |
          helm install dotnet-todo ./helm-chart/dotnet-todo

      - name: Verify Kubernetes Resources
        run: |
          kubectl get all

      - name: Wait for Service to be Available
        run: |
          echo "Waiting for the service to be available..."
          sleep 30
          kubectl get services

      - name: Port-Forward and Run Tests
        run: |
          kubectl port-forward service/dotnet-todo 8080:80 &
          sleep 10
          curl http://localhost:8080/api/todo
