name: minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build Docker image
        run: docker build -t dotnet-todo:${{ github.sha }} .

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mkdir -p /usr/local/bin/
          sudo install minikube /usr/local/bin/
          sudo minikube start --driver=none --kubernetes-version=v1.21.14
          minikube status

      - name: Deploy to Minikube using Helm
        run: |
          helm install dotnet-todo ./helm-chart/dotnet-todo

      - name: Run Tests
        run: |
          kubectl port-forward service/dotnet-todo 8080:80 &
          sleep 5
          curl http://localhost:8080/api/todo
