name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
         
          driver: docker

      - name: Helm Install
        run: 
          helm install myapp ./helm-chart

      - name: Get Pods Status
        run: kubectl get pods

      - name: Test Application
        run: 
          kubectl port-forward service/myapp 8080:80 &
          curl http://localhost:8080/todo
