name: minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Docker image
        run: docker build -t devoops39/dotnet-todo:${{ github.sha }} .

      - name: Tag Docker image as latest
        run: docker tag devoops39/dotnet-todo:${{ github.sha }} devoops39/dotnet-todo:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag devoops39/dotnet-todo:${{ github.sha }} your-dockerhub-username/dotnet-todo:latest
          docker push devoops39/dotnet-todo:${{ github.sha }}
          docker push devoops39/dotnet-todo:latest

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat

      - name: Set up Minikube with Docker Driver
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/
          minikube start --driver=docker --kubernetes-version=v1.21.14

      - name: Deploy to Minikube using Helm
        run: |
          helm install dotnet-todo ./helm-chart/dotnet-todo --set image.repository=devoops39/dotnet-todo --set image.tag=${{ github.sha }}

      - name: Check Helm Release Status
        run: helm status dotnet-todo

      - name: List All Services
        run: kubectl get services --all-namespaces

      - name: Check Pod Status
        run: kubectl get pods

      - name: Wait for Service to be Available
        run: |
          echo "Waiting for the service to be available..."
          sleep 30
          kubectl get services

      - name: Port-Forward and Run Tests
        run: |
          kubectl port-forward service/dotnet-todo 8080:80 &
          sleep 10
          curl http://localhost:8080/api/todo
