name: Minikube Kubernetes Cluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

      - name: Install crictl
        run: |
          VERSION="v1.28.0"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-$VERSION-linux-amd64.tar.gz
          rm crictl-$VERSION-linux-amd64.tar.gz

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          minikube status

      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Deploy a sample application
        run: |
          kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
          kubectl expose deployment hello-minikube --type=NodePort --port=8080

      - name: Get application URL
        run: |
          minikube service hello-minikube --url
