name: minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Docker image
        run: docker build -t dotnet-todo:${{ github.sha }} .

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2

      - name: Deploy to Minikube
        run: |
          helm install dotnet-todo ./helm-chart/dotnet-todo

      - name: Run Tests
        run: |
          curl http://localhost:8080/api/todo
