name: minikube

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Docker image
        run: docker build -t devoops39/dotnet-todo:${{ github.sha }} .

      - name: Tag Docker image as latest
        run: docker tag devoops39/dotnet-todo:${{ github.sha }} devoops39/dotnet-todo:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag devoops39/dotnet-todo:${{ github.sha }} devoops39/dotnet-todo:latest
          docker push devoops39/dotnet-todo:${{ github.sha }}
          docker push devoops39/dotnet-todo:latest

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat

      - name: Set up Minikube with Docker Driver
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/
          minikube start --driver=docker --kubernetes-version=v1.30.4

      - name: Attempt to Upgrade Helm Release
        run: |
         helm upgrade dotnet-todo ./helm-chart/dotnet-todo --set image.repository=devoops39/dotnet-todo --set image.tag=${{ github.sha }} || \
         helm install dotnet-todo ./helm-chart/dotnet-todo --set image.repository=devoops39/dotnet-todo --set image.tag=${{ github.sha }}

      - name: Check Helm Release Status
        run: helm status dotnet-todo

      - name: List All Services
        run: kubectl get services --all-namespaces

      - name: Check Pod Status
        run: kubectl get pods

      - name: Wait for Service to be Available
        run: |
          echo "Waiting for the service to be available..."
          sleep 30
          kubectl get services

      - name: Check Pod Logs
        run: |
         POD_NAME=$(kubectl get pods --selector=app.kubernetes.io/name=dotnet-todo --output=jsonpath="{.items[0].metadata.name}")
         echo "Checking logs for pod $POD_NAME"
         kubectl logs $POD_NAME

      - name: Test Application Inside Pod
        run: |
          POD_NAME=$(kubectl get pods --selector=app.kubernetes.io/name=dotnet-todo --output=jsonpath="{.items[0].metadata.name}")
          echo "Testing application inside pod $POD_NAME"
          kubectl exec  $POD_NAME -- curl -s http://localhost:8080 || echo "Application not responding on port 8080 inside the pod"

      - name: Port-Forward and Run Tests
        run: |
          kubectl port-forward service/dotnet-todo-dotnet-todo 8080:8080 &
          sleep 10
          curl http://localhost:8080/api/todo || echo "Port-forwarding failed or application not responding"
